//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class member101
    {
        public decimal member_id { get; set; }
        public string member_name { get; set; }
        public Nullable<System.DateTime> Acc_open_date { get; set; }
        public Nullable<decimal> maxbooksallowed { get; set; }
        public Nullable<decimal> penaltyamount { get; set; }
    }
}
